// <auto-generated />
using GenericRepositoryDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GenericRepositoryDemo.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20181124141449_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GenericRepositoryDemo.Models.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new { Id = 1, Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ut leo eu tortor pretium malesuada.", Title = "Lorem Ipsum" },
                        new { Id = 2, Description = "Vestibulum nec magna eu tortor ullamcorper iaculis. Vivamus faucibus volutpat varius. ", Title = "Dolor Sit" },
                        new { Id = 3, Description = "Ut ultricies sollicitudin nibh, sit amet ultricies orci faucibus eu. Duis eu nisl dolor. Vestibulum quam velit, aliquam id dictum a, rutrum eu sem. ", Title = "Consectetur" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
